### ISSUE TITLE
请问这个报错怎么解决

### ISSUE THREAD

**Issue by hbx111** [mrathena/python.pubg.weapon.auto.recognize.and.suppress#1]
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

**Comment by mrathena** [comment]
详细细节贴一下, 还有在源码中的文件和行号
